language: node_js

node_js:
- stable

addons:
  apt:
    packages:
    - gcc
    - g++
    - libstdc++6
    - pulseaudio

cache:
  directories:
  - $HOME/.npm
  - node_modules

deploy:
- provider: npm
  email: kirill.konshin@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    node: 6
    tags: true
    repo: ringcentral/ringcentral-web-phone
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - src/ringcentral-web-phone.js
  on:
    node: 6
    tags: true
    repo: ringcentral/ringcentral-web-phone

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pulseaudio --start

env:
  global:
  - DISPLAY=:99.0