name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: DEBUG=eslint:cli-engine yarn run lint:all
      - run: yarn run build
      - run: yarn run test:ut
      - name: E2E test
        env:
          RC_WP_CALLER_CLIENT_ID: ${{ secrets.RC_WP_CALLER_CLIENT_ID }}
          RC_WP_CALLER_CLIENT_SECRET: ${{ secrets.RC_WP_CALLER_CLIENT_SECRET }}
          RC_WP_CALLER_SERVER: ${{ secrets.RC_WP_CALLER_SERVER }}
          RC_WP_RECEIVER_CLIENT_ID: ${{ secrets.RC_WP_RECEIVER_CLIENT_ID }}
          RC_WP_RECEIVER_CLIENT_SECRET: ${{ secrets.RC_WP_RECEIVER_CLIENT_SECRET }}
          RC_WP_RECEIVER_SERVER: ${{ secrets.RC_WP_RECEIVER_SERVER }}
          RC_WP_CALLER_USERNAME: ${{ secrets.RC_WP_CALLER_USERNAME }}
          RC_WP_CALLER_EXTENSION: ${{ secrets.RC_WP_CALLER_EXTENSION }}
          RC_WP_CALLER_PASSWORD: ${{ secrets.RC_WP_CALLER_PASSWORD }}
          RC_WP_RECEIVER_USERNAME: ${{ secrets.RC_WP_RECEIVER_USERNAME }}
          RC_WP_RECEIVER_EXTENSION: ${{ secrets.RC_WP_RECEIVER_EXTENSION }}
          RC_WP_RECEIVER_PASSWORD: ${{ secrets.RC_WP_RECEIVER_PASSWORD }}
        if: ${{ env.RC_WP_CALLER_CLIENT_ID != '' && env.RC_WP_RECEIVER_PASSWORD != '' &&  env.RC_WP_CALLER_PASSWORD != '' }}
        run: |
          yarn run test:e2e
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage/lcov.info
      - name: Github Pages
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
